version: 2
updates:
  - package-ecosystem: "maven"
    directories: 
      - "/code"
      - "/code/api-rest"
      - "/code/application"
      - "/code/boot"
      - "/code/coverage"
      - "/code/domain"
      - "/code/infrastructure"
    assignees:
      - "fedykvitalik2004"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[maven] "

  - package-ecosystem: "docker"
    directory: "/code"
    assignees:
      - "fedykvitalik2004"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[docker] "

  - package-ecosystem: "docker-compose"
    directory: "/code"
    assignees:
      - "fedykvitalik2004"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[docker-compose] "
